<#
.SYNOPSIS
    Creates an encrypted credential file for use with MeditechMasterScript.ps1.
.DESCRIPTION
    Interactively collects MBF credentials, RSC service account details, and backup
    configuration, then exports everything as a DPAPI-encrypted XML file using
    PowerShell's Export-Clixml.

    The resulting file can ONLY be decrypted by the same Windows user account on the
    same machine — making it safe for use with Task Scheduler. Sensitive fields
    (MBF password, RSC client secret) are stored as SecureString and encrypted by
    DPAPI. Non-sensitive fields (client ID, token URI, SLA ID, etc.) are stored as
    plain strings in the same object.

    Run this script once, interactively, as the service account that Task Scheduler
    will use. Then point MeditechMasterScript.ps1 at the output file via -MbfConfigXml.
.PARAMETER OutputPath
    Path where the encrypted credential file will be written.
    Defaults to C:\ProgramData\Rubrik\MeditechCreds.xml
.EXAMPLE
    # Run interactively as the Task Scheduler service account
    .\New-MeditechCredentials.ps1

    # Or specify a custom output path
    .\New-MeditechCredentials.ps1 -OutputPath "D:\Rubrik\mbf-creds.xml"
.EXAMPLE
    # After setup, the main script needs only a single argument for Task Scheduler
    .\MeditechMasterScript.ps1 -MbfConfigXml "C:\ProgramData\Rubrik\MeditechCreds.xml" -EnableLogging
.NOTES
    Author  : Marcus Henderson
    Created : March 2026
    Company : Rubrik Inc

    SECURITY NOTE:
    The output XML uses Windows DPAPI (Data Protection API) to encrypt the MBF
    password and RSC client secret. Both are tied to the current user account and
    machine. If you need to run as a different user or on a different machine,
    re-run this script under that context to generate a new XML file.

    NOTE ON EXISTING XML FILES:
    This version of the setup script stores RSC credentials alongside MBF credentials.
    If you have an XML file generated by an older version of this script, regenerate
    it by running this script again.
#>
param (
    [Parameter()]
    [string]$OutputPath = "C:\ProgramData\Rubrik\MeditechCreds.xml"
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=== Meditech Credential Setup ===" -ForegroundColor Cyan
Write-Host "All credentials will be DPAPI-encrypted and stored at:"
Write-Host "  $OutputPath" -ForegroundColor Yellow
Write-Host ""
Write-Host "IMPORTANT: Run this script as the same user account that Task Scheduler" -ForegroundColor Magenta
Write-Host "           will use to execute MeditechMasterScript.ps1." -ForegroundColor Magenta
Write-Host ""

# -----------------------------------------------------------------------------
# STEP 1: MBF CREDENTIALS
# -----------------------------------------------------------------------------
Write-Host "Step 1 of 5: MBF Credentials" -ForegroundColor Cyan
Write-Host "        The password will be masked and DPAPI-encrypted in the output file." -ForegroundColor Gray

$mbfCredential = Get-Credential -Message "Enter MBF Username and Password"

if (-not $mbfCredential) {
    Write-Error "No MBF credential provided. Aborting."
    exit 1
}

# -----------------------------------------------------------------------------
# STEP 2: MBF INTERMEDIARY
# -----------------------------------------------------------------------------
Write-Host ""
Write-Host "Step 2 of 5: MBF Intermediary host(s)" -ForegroundColor Cyan
Write-Host "        For a single intermediary : RUB-MBI:2987" -ForegroundColor Gray
Write-Host "        For multiple intermediaries: RUB-MBI:2987,RUB-MATFS:2987" -ForegroundColor Gray
Write-Host ""

$intermediaryInput = (Read-Host "MBF Intermediary").Trim().Trim('"').Trim("'")

if ([string]::IsNullOrWhiteSpace($intermediaryInput)) {
    Write-Error "Intermediary cannot be empty. Aborting."
    exit 1
}

$intermediaryNormalized = (($intermediaryInput -split ',') | ForEach-Object { $_.Trim() } | Where-Object { $_ }) -join ","

# -----------------------------------------------------------------------------
# STEP 3: RSC SERVICE ACCOUNT
# -----------------------------------------------------------------------------
Write-Host ""
Write-Host "Step 3 of 5: RSC Service Account" -ForegroundColor Cyan
Write-Host "        Load from an existing service account JSON file, or enter values manually." -ForegroundColor Gray
Write-Host "        The client secret will be DPAPI-encrypted in the output file." -ForegroundColor Gray
Write-Host ""

$rscJsonPath = (Read-Host "Path to RSC service account JSON (press Enter to enter manually)").Trim().Trim('"').Trim("'")

$rscClientId     = $null
$rscTokenUri     = $null
$rscName         = $null
$rscClientSecret = $null

if (-not [string]::IsNullOrWhiteSpace($rscJsonPath)) {
    if (-not (Test-Path $rscJsonPath)) {
        Write-Error "File not found: '$rscJsonPath'. Aborting."
        exit 1
    }
    try {
        $rscJson = Get-Content -Raw $rscJsonPath | ConvertFrom-Json
    } catch {
        Write-Error "Failed to parse RSC service account JSON: $_"
        exit 1
    }
    $rscClientId     = $rscJson.client_id
    $rscTokenUri     = $rscJson.access_token_uri
    $rscName         = $rscJson.name
    $rscClientSecret = $rscJson.client_secret | ConvertTo-SecureString -AsPlainText -Force

    Write-Host "    Loaded from file." -ForegroundColor Gray
    Write-Host "    Name      : $rscName" -ForegroundColor Gray
    Write-Host "    Client ID : $rscClientId" -ForegroundColor Gray
    Write-Host "    Token URI : $rscTokenUri" -ForegroundColor Gray
} else {
    Write-Host ""
    $rscClientId     = (Read-Host "RSC Client ID").Trim().Trim('"').Trim("'")
    $rscTokenUri     = (Read-Host "RSC Access Token URI").Trim().Trim('"').Trim("'")
    $rscName         = (Read-Host "RSC Service Account Name (optional, for reference)").Trim().Trim('"').Trim("'")
    $rscClientSecret = Read-Host "RSC Client Secret" -AsSecureString
}

if ([string]::IsNullOrWhiteSpace($rscClientId) -or [string]::IsNullOrWhiteSpace($rscTokenUri)) {
    Write-Error "RSC Client ID and Access Token URI are required. Aborting."
    exit 1
}

# -----------------------------------------------------------------------------
# STEP 4: RETENTION SLA ID
# -----------------------------------------------------------------------------
Write-Host ""
Write-Host "Step 4 of 5: RSC Retention SLA ID" -ForegroundColor Cyan
Write-Host "        The UUID of the SLA domain snapshots will be retained under." -ForegroundColor Gray
Write-Host "        Run MeditechMasterScript.ps1 with -ListSlas to find this value." -ForegroundColor Gray
Write-Host ""

$retentionSlaId = (Read-Host "Retention SLA ID (UUID)").Trim().Trim('"').Trim("'")

if ([string]::IsNullOrWhiteSpace($retentionSlaId)) {
    Write-Error "Retention SLA ID cannot be empty. Aborting."
    exit 1
}

# -----------------------------------------------------------------------------
# STEP 5: GCP PROJECT ID (OPTIONAL)
# -----------------------------------------------------------------------------
Write-Host ""
Write-Host "Step 5 of 5: GCP Project ID Filter (optional)" -ForegroundColor Cyan
Write-Host "        Limits the RSC inventory search to a specific GCP project." -ForegroundColor Gray
Write-Host "        Run MeditechMasterScript.ps1 with -ListProjects to find this value." -ForegroundColor Gray
Write-Host "        Press Enter to skip (all projects will be searched)." -ForegroundColor Gray
Write-Host ""

$gcpProjectIdInput = (Read-Host "GCP Project ID (or press Enter to skip)").Trim().Trim('"').Trim("'")
$gcpProjectId = if ([string]::IsNullOrWhiteSpace($gcpProjectIdInput)) { $null } else { $gcpProjectIdInput }

# -----------------------------------------------------------------------------
# ENSURE OUTPUT DIRECTORY EXISTS
# -----------------------------------------------------------------------------
$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outputDir)) {
    try {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
        Write-Host "Created directory: $outputDir" -ForegroundColor Gray
    } catch {
        Write-Error "Could not create output directory '$outputDir': $_"
        exit 1
    }
}

# -----------------------------------------------------------------------------
# BUILD AND EXPORT
# -----------------------------------------------------------------------------
# Export-Clixml DPAPI-encrypts SecureString fields (MBF password, RSC client secret).
# All other fields are stored as plain strings — they are not sensitive secrets.
$credStore = [PSCustomObject]@{
    # MBF
    MbfCredential   = $mbfCredential           # PSCredential  — DPAPI encrypted
    MbfIntermediary = $intermediaryNormalized   # plain string

    # RSC Service Account
    RscClientId     = $rscClientId             # plain string
    RscClientSecret = $rscClientSecret         # SecureString  — DPAPI encrypted
    RscTokenUri     = $rscTokenUri             # plain string
    RscName         = $rscName                 # plain string

    # Backup Configuration
    RetentionSlaId  = $retentionSlaId          # plain string
    GcpProjectId    = $gcpProjectId            # plain string or $null
}

try {
    $credStore | Export-Clixml -Path $OutputPath -Force
} catch {
    Write-Error "Failed to write credential file: $_"
    exit 1
}

Write-Host ""
Write-Host "=== Setup Complete ===" -ForegroundColor Green
Write-Host "Credential file written to : $OutputPath" -ForegroundColor Green
Write-Host ""
Write-Host "Encrypted for user    : $env:USERDOMAIN\$env:USERNAME" -ForegroundColor Yellow
Write-Host "Encrypted for machine : $env:COMPUTERNAME" -ForegroundColor Yellow
Write-Host ""
Write-Host "Task Scheduler invocation:" -ForegroundColor Cyan
Write-Host "  .\MeditechMasterScript.ps1 ``" -ForegroundColor Gray
Write-Host "      -MbfConfigXml `"$OutputPath`" ``" -ForegroundColor Gray
Write-Host "      -EnableLogging" -ForegroundColor Gray
Write-Host ""
Write-Host "To list SLA domains (uses RSC creds from XML):" -ForegroundColor Cyan
Write-Host "  .\MeditechMasterScript.ps1 -MbfConfigXml `"$OutputPath`" -ListSlas" -ForegroundColor Gray
Write-Host ""
